### ISSUE TITLE
spawning.run_controller MIA

### ISSUE THREAD

**Issue by dunkfordyce** [rtyler/Spawning#24] opened 2010-10-17 08:19 UTC
Using spawning obtained via easy_install:

```
Starting server in PID 27414.
Traceback (most recent call last):
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/exe.py", line 107, in run
    command.run(options)
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/serve.py", line 303, in command
    serve()
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/serve.py", line 287, in serve
    server(app)
  File "/data/dunk/projects/xxxxx/branches/cssanywhere/xxxxx/devenv2/lib/python2.5/site-packages/Spawning-0.9.5-py2.5.egg/spawning/paste_factory.py", line 99, in run
    spawning_controller.run_controller(
AttributeError: 'module' object has no attribute 'run_controller'
```

**Comment by rtyler** [comment] 2010-10-18 23:59
This is a duplicate of #19

**Closed as completed by rtyler** 2010-10-18 23:59 UTC
